name: Hello World

on:
  workflow_dispatch:

jobs:
  hello-world:
    name: Hello World
    runs-on: ubuntu-latest
    steps:
    - name: Context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
    - name: Checkout
      uses: actions/checkout@v2
    - name: Hello World
      run: |
        echo "Hello World"
